import { arxivScraper } from '../services/arxivScraper';
import { pubmedScraper } from '../services/pubmedScraper';
import { crossrefScraper } from '../services/crossrefScraper';
import logger from '../utils/logger';

export async function runDailyScraping() {
  try {
    logger.info('Running daily scraping job...');
    
    const topics = [
      'machine learning',
      'deep learning',
      'computer vision',
      'natural language processing',
      'artificial intelligence',
      'data science',
      'robotics',
      'bioinformatics',
      'quantum computing',
      'cybersecurity',
      'renewable energy',
      'climate change',
      'sustainable development',
      'blockchain',
      'internet of things',
      'augmented reality',
      'virtual reality',
      '5G technology',
      'edge computing',
      'cloud computing',
      'quantum computing',
      'human-computer interaction',
      'big data',
      'autonomous vehicles',
      'smart cities',
      'digital health',
      'genomics',
      'nanotechnology',
      'space exploration',
      'financial technology',
      'educational technology',
      'social media analysis',
      'e-commerce',
      'supply chain management',
      'wearable technology',
      '3D printing',
      'renewable energy technologies',
      'environmental monitoring',
      'telecommunications',
      'photovoltaics',
      'energy storage',
      'smart grids',
      'urban planning',
      'public health',
      'epidemiology',
      'mental health technologies',
      'telemedicine',
      'digital therapeutics',
      'computational biology',
      'synthetic biology',
      'drug discovery',
      'precision medicine',
      'medical imaging',
      'health informatics',
      'robotic surgery',
      'assistive technologies',
      'food technology',
      'agricultural technology',
      'climate modeling',
      'oceanography',
      'geospatial technologies',
      'disaster management',
      'crisis informatics',
      'humanitarian technology',
      'digital inclusion',
      'technology policy',
      'ethics in technology',
      'technology and society',
      'digital transformation',
      'innovation management',
      'technology entrepreneurship',
      'research and development management',
      'technology foresight',
      'science and technology studies',
      'technology assessment',
      'technology diffusion',
      'technology adoption',
      'technology transfer',
      'intellectual property in technology',
      'technology commercialization',
      'science communication',
      'public engagement with science and technology',
      'citizen science',
      'open science',
      'open data',
      'open source software',
      'collaborative research',
      'interdisciplinary research',
      'transdisciplinary research',
      'team science',
      'research ethics',
      'responsible research and innovation',
      'sustainable technology development',
      'green technology',
      'clean technology',
      'environmentally sustainable technology',
      'socially responsible technology',
      'inclusive technology',
      'accessible technology',
      'human-centered technology',
      'user experience design',
      'interaction design',
      'service design',
      'design thinking',
      'innovation ecosystems',
      'technology hubs',
      'science parks',
      'research infrastructure',
      'digital infrastructure',
      'broadband access',
      'digital divide',
      'technology literacy',
      'digital skills development',
      'technology education',
      'STEM education',
      'computational thinking',
      'coding education',
      'robotics education',
      'maker education',
      'DIY technology',
      'hacker culture',
      'tech activism',
      'digital rights',
      'data privacy',
      'cyber ethics',
      'information security',
      'network security',
      'cryptography',
      'blockchain security',
      'quantum cryptography',
      'post-quantum cryptography',
      'secure communications',
      'cyber warfare',
      'cyber defense',
      'national security and technology',
      'technology in defense',
      'military technology',
      'aerospace technology',
      'defense systems',
      'surveillance technology',
      'intelligence technology',
      'counterterrorism technology',
      'emerging technologies in security',
      'technology policy and regulation',
      'technology governance',
      'international technology policy',
      'technology and human rights',
      'technology and democracy',
      'digital governance',
      'e-governance',
      'smart governance',
      'technology for development',
      'ICT4D (Information and Communication Technologies for Development)',
      'technology and poverty alleviation',
      'technology and social justice',
      'technology and equality',
      'technology and inclusion',
      'technology and empowerment',
      'technology and community development',
      'technology and cultural heritage',
      'digital humanities',
      'technology in the arts',
      'creative technologies',
      'media technology',
      'communication technology',
      'journalism and technology',
      'digital storytelling',
      'virtual communities',
      'online social networks',
      'digital identity',
      'online privacy',
      'internet governance',
      'net neutrality',
      'digital economy',
      'e-business',
      'digital marketing',
      'online advertising',
      'social media marketing',
      'influencer marketing',
      'content marketing',
      'search engine optimization (SEO)',
      'web analytics',
      'data-driven marketing',
      'marketing automation',
      'customer relationship management (CRM)',
      'e-commerce platforms',
      'online payment systems',
      'digital supply chain management',
      'logistics technology',
      'inventory management technology',
      'retail technology',
      'omnichannel retailing',
      'mobile commerce',
      'social commerce',
      'subscription commerce',
      'digital product management',
      'agile product development',
      'lean startup methodology',
      'minimum viable product (MVP)',
      'product-market fit',
      'growth hacking',
      'user acquisition',
      'customer retention',
      'churn reduction',
      'lifecycle marketing',
      'data science in marketing',
      'marketing analytics',
      'predictive analytics in marketing',
      'big data in marketing',
      'artificial intelligence in marketing',
      'machine learning in marketing',
      'chatbots in marketing',
      'voice assistants in marketing',
      'virtual reality in marketing',
      'augmented reality in marketing',
      'blockchain in marketing',
      'internet of things in marketing',
      '5G in marketing',
      'edge computing in marketing',
      'cloud computing in marketing'
    ];
    
    for (const topic of topics) {
      await arxivScraper.scrapeArticles(topic, 100);
      await new Promise(resolve => setTimeout(resolve, 5000));

      // PubMed
      await pubmedScraper.scrapeArticles(topic, 20);
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // CrossRef
      await crossrefScraper.scrapeArticles(topic, 20);
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
    
    logger.info('Daily scraping completed');
  } catch (error) {
    logger.error('Daily scraping failed:', error);
  }
}